set nocompatible
execute pathogen#infect()

syntax enable

set background=dark
colorscheme solarized

set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set ruler
set ignorecase
set hlsearch
set noerrorbells
set novisualbell
set number
set cursorline

filetype plugin indent on

autocmd vimenter * if !argc() | NERDTree | endif

let g:vim_markdown_folding_disabled=1

inoremap jj <esc>
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

let g:airline_powerline_fonts = 1
set guifont=Inconsolata\ for\ Powerline:h15
let g:Powerline_symbols = 'fancy'
set encoding=utf-8
set t_Co=256
set fillchars+=stl:\ ,stlnc:\
set term=xterm-256color
set termencoding=utf-8
